### ISSUE TITLE
Unable to get unbound to work

### ISSUE THREAD

**Issue by khadanja** [hat3ph/docker-adguard-unbound#3]
Followed the youtube video, trying to setup on a ubuntu VM in virtualBox. AgH works fine with the default dns server in upstream but when I put 127.0.0.1:5053, test upstream fails. 
2023/02/06 06:57:13.550004 [info] upstream "127.0.0.1:5053" fails to exchange: couldn't communicate with upstream: read udp 127.0.0.1:58039->127.0.0.1:5053: i/o timeout
Server "127.0.0.1:5053": could not be used, please check that you've written it correctly

**Comment by hat3ph** [comment]
Are you using unbound dns with local port 5053?

Run command "sudo lsof -P -i -n" in terminal and provide the output. You may need to install lsof package if not installed.

**Comment by khadanja** [comment]
> sudo lsof -P -i -n

Yes I believe so as I am using your files from the repo. unbound.conf has port set to 5053. 
```
sudo lsof -P -i -n
COMMAND    PID            USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
sshd       702            root    3u  IPv4  20371      0t0  TCP *:22 (LISTEN)
sshd       702            root    4u  IPv6  20373      0t0  TCP *:22 (LISTEN)
sshd       967            root    4u  IPv4  21030      0t0  TCP 192.168.1.36:22->192.168.1.6:5626 (ESTABLISHED)
sshd      1072          lakhan    4u  IPv4  21030      0t0  TCP 192.168.1.36:22->192.168.1.6:5626 (ESTABLISHED)
docker-pr 1167            root    4u  IPv4  22631      0t0  TCP *:9443 (LISTEN)
docker-pr 1173            root    4u  IPv6  21254      0t0  TCP *:9443 (LISTEN)
docker-pr 1185            root    4u  IPv4  22656      0t0  TCP *:8000 (LISTEN)
docker-pr 1192            root    4u  IPv6  22661      0t0  TCP *:8000 (LISTEN)
docker-pr 2956            root    4u  IPv4  29985      0t0  TCP *:3000 (LISTEN)
docker-pr 2962            root    4u  IPv6  29165      0t0  TCP *:3000 (LISTEN)
docker-pr 2975            root    4u  IPv4  29178      0t0  TCP *:80 (LISTEN)
docker-pr 2982            root    4u  IPv6  29181      0t0  TCP *:80 (LISTEN)
docker-pr 2996            root    4u  IPv4  30023      0t0  TCP *:53 (LISTEN)
docker-pr 3002            root    4u  IPv6  29207      0t0  TCP *:53 (LISTEN)
docker-pr 3015            root    3u  IPv4  33884      0t0  UDP 172.18.0.1:52528->172.18.0.2:53
docker-pr 3015            root    4u  IPv4  29249      0t0  UDP *:53
docker-pr 3015            root    8u  IPv4  34098      0t0  UDP 172.18.0.1:34996->172.18.0.2:53
docker-pr 3021            root    4u  IPv6  29251      0t0  UDP *:53
systemd-n 4406 systemd-network   18u  IPv4  35118      0t0  UDP 192.168.1.36:68

```

**Comment by hat3ph** [comment]
@khadanja , I don't see TCP/UDP 5053 port running. Did you enable the unbound port in the docker-compose.yml? By default the 5053 port is disabled in the YAML file, you need to enable it to use unbound. I have also update the README file regarding this too just in case.
Pls share your docker-compose.yml.

**Comment by khadanja** [comment]
@hat3ph That was the confusing part for me as your github docker-compose has 5035 disabled not 5053. Also in the video you did not enable but still for you 127.0.0.1:5053 worked. Is it supposed to be 5053 or 5035? I have just now enabled 5053 in docker-compose & can see TCP/UDP 5053 port running but still same issue. docker-compose & lsof output below.
```
2023/02/08 00:40:36.693916 [info] upstream "127.0.0.1:5053" fails to exchange: couldn't communicate with upstream: read udp 127.0.0.1:39508->127.0.0.1:5053: read: connection refused
```
```
`version: "3"
services:
  adguard-unbound:
    container_name: adguard-unbound
    image: lolgast/adguard-unbound
    restart: unless-stopped
    hostname: adguard-unbound
    # Volumes store your data between container upgrades
    volumes:
      - "./adguard/opt-adguard-work:/opt/adguardhome/work" # adguard container work directory
      - "./adguard/opt-adguard-conf:/opt/adguardhome/conf" # adguard container conf directory
      - "./unbound:/opt/unbound" # map custom unbound config
      - "/usr/share/dns:/usr/share/dns" # map DNSSEC key and root hints from dns-root-data package
    ports:
      - 53:53/tcp # AdGuard Home DNS connection
      - 53:53/udp # AdGuard Home DNS connection
      - 3000:3000/tcp # AdGuard Home install web panel. Can disable after installation is completed.
      - 80:80/tcp # AdGuard Home web panel HTTP
      #- 443:443/tcp # AdGuard Home web panel HTTPS
      #- 784:784/udp # AdGuard Home DNS-over-QUIC service
      #- 853:853/tcp # AdGuard Home DNS-over-TLS/QUIC service
      #- 67:67/udp # DHCP server
      #- 68:68/udp # DHCP server
      - 5053:5053/tcp # Uncomment to enable unbound access on local server
      - 5053:5053/udp # Uncomment to enable unbound access on local server`
```

```
COMMAND    PID            USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
systemd-n  627 systemd-network   18u  IPv4  19280      0t0  UDP 192.168.1.36:68
sshd       702            root    3u  IPv4  20371      0t0  TCP *:22 (LISTEN)
sshd       702            root    4u  IPv6  20373      0t0  TCP *:22 (LISTEN)
sshd       967            root    4u  IPv4  21030      0t0  TCP 192.168.1.36:22->192.168.1.6:5626 (ESTABLISHED)
sshd      1072          lakhan    4u  IPv4  21030      0t0  TCP 192.168.1.36:22->192.168.1.6:5626 (ESTABLISHED)
docker-pr 1167            root    4u  IPv4  22631      0t0  TCP *:9443 (LISTEN)
docker-pr 1173            root    4u  IPv6  21254      0t0  TCP *:9443 (LISTEN)
docker-pr 1185            root    4u  IPv4  22656      0t0  TCP *:8000 (LISTEN)
docker-pr 1192            root    4u  IPv6  22661      0t0  TCP *:8000 (LISTEN)
sshd      1279            root    4u  IPv4  21400      0t0  TCP 192.168.1.36:22->192.168.1.6:2542 (ESTABLISHED)
sshd      1335          lakhan    4u  IPv4  21400      0t0  TCP 192.168.1.36:22->192.168.1.6:2542 (ESTABLISHED)
docker-pr 3368            root    4u  IPv4  40630      0t0  TCP *:5053 (LISTEN)
docker-pr 3374            root    4u  IPv6  40635      0t0  TCP *:5053 (LISTEN)
docker-pr 3391            root    4u  IPv4  40691      0t0  UDP *:5053
docker-pr 3398            root    4u  IPv6  40695      0t0  UDP *:5053
docker-pr 3413            root    4u  IPv4  40732      0t0  TCP *:3000 (LISTEN)
docker-pr 3420            root    4u  IPv6  40737      0t0  TCP *:3000 (LISTEN)
docker-pr 3438            root    4u  IPv4  41396      0t0  TCP *:80 (LISTEN)
docker-pr 3444            root    4u  IPv6  41401      0t0  TCP *:80 (LISTEN)
docker-pr 3459            root    4u  IPv4  40797      0t0  TCP *:53 (LISTEN)
docker-pr 3465            root    4u  IPv6  40802      0t0  TCP *:53 (LISTEN)
docker-pr 3481            root    4u  IPv4  40858      0t0  UDP *:53
docker-pr 3487            root    4u  IPv6  40862      0t0  UDP *:53

```
