### ISSUE TITLE
[error] exec /opt/entrypoint.sh: exec format error

### ISSUE THREAD

**Issue by FelixBorgel** [hat3ph/docker-adguard-unbound#6]
i can´t start the docker. This is in the log of the docker container. What can i do to fix the problem.

**Comment by hat3ph** [comment]
Are you using docker compose? Pls post the output of docker compose logs.

**Comment by FelixBorgel** [comment]
That's basically what it says, just now 984 times.

**Comment by FelixBorgel** [comment]
and yes im using docker compose

**Comment by hat3ph** [comment]
I have setup the container on a fresh Ubuntu 24.04 and it is working with out issue.
What is your docker host distro?

```
administrator@ubuntu-svr:~/docker-adguard-unbound$ docker compose logs
WARN[0000] /home/administrator/docker-adguard-unbound/docker-compose.yml: `version` is obsolete 
adguard-unbound  | 2024/06/19 22:54:03.130936 [info] AdGuard Home, version v0.107.51
adguard-unbound  | 2024/06/19 22:54:03.130991 [info] This is the first time AdGuard Home is launched
adguard-unbound  | 2024/06/19 22:54:03.130994 [info] Checking if AdGuard Home has necessary permissions
adguard-unbound  | 2024/06/19 22:54:03.131398 [info] AdGuard Home can bind to port 53
adguard-unbound  | 2024/06/19 22:54:03.133602 [info] safesearch default: disabled
adguard-unbound  | 2024/06/19 22:54:03.135817 [info] Initializing auth module: /opt/adguardhome/work/data/sessions.db
adguard-unbound  | 2024/06/19 22:54:03.139587 [info] auth: initialized.  users:0  sessions:0
adguard-unbound  | 2024/06/19 22:54:03.139680 [info] AdGuard Home updates are disabled
adguard-unbound  | 2024/06/19 22:54:03.139685 [info] web: initializing
adguard-unbound  | 2024/06/19 22:54:03.139709 [info] This is the first launch of AdGuard Home, redirecting everything to /install.html 
adguard-unbound  | 2024/06/19 22:54:03.139731 [info] AdGuard Home is available at the following addresses:
adguard-unbound  | 2024/06/19 22:54:03.139877 [info] go to http://127.0.0.1:3000
adguard-unbound  | 2024/06/19 22:54:03.139881 [info] go to http://[::1]:3000
adguard-unbound  | 2024/06/19 22:54:03.139883 [info] go to http://172.18.0.2:3000
adguard-unbound  | 2024/06/19 22:56:08.534797 [info] WARNING: preparing resolvers: no upstream specified; trying to disable private RDNS resolution
adguard-unbound  | 2024/06/19 22:56:08.534853 [info] dnsproxy: cache: enabled, size 4096 b
adguard-unbound  | 2024/06/19 22:56:08.534857 [info] dnsproxy: max goroutines is set to 300
adguard-unbound  | 2024/06/19 22:56:08.534885 [info] Ratelimit is enabled and set to 20 rps, IPv4 subnet mask len 24, IPv6 subnet mask len 56
adguard-unbound  | 2024/06/19 22:56:08.534887 [info] dnsproxy: server will refuse requests of type ANY
adguard-unbound  | 2024/06/19 22:56:08.534897 [info] dnsproxy: cache: enabled, size 4194304 b
adguard-unbound  | 2024/06/19 22:56:08.534900 [info] dnsproxy: max goroutines is set to 300
adguard-unbound  | 2024/06/19 22:56:08.538301 [info] clients: processing addresses
adguard-unbound  | 2024/06/19 22:56:08.541409 [info] dnsproxy: starting dns proxy server
adguard-unbound  | 2024/06/19 22:56:08.541432 [info] dnsproxy: creating udp server socket 0.0.0.0:53
adguard-unbound  | 2024/06/19 22:56:08.541553 [info] dnsproxy: listening to udp://[::]:53
adguard-unbound  | 2024/06/19 22:56:08.541560 [info] dnsproxy: creating tcp server socket 0.0.0.0:53
adguard-unbound  | 2024/06/19 22:56:08.541614 [info] dnsproxy: listening to tcp://[::]:53
adguard-unbound  | 2024/06/19 22:56:08.541726 [info] dnsproxy: entering udp listener loop on [::]:53
adguard-unbound  | 2024/06/19 22:56:08.541811 [info] dnsproxy: entering tcp listener loop on [::]:53
adguard-unbound  | 2024/06/19 22:56:08.548429 [info] go to http://127.0.0.1:80
adguard-unbound  | 2024/06/19 22:56:08.548452 [info] go to http://[::1]:80
adguard-unbound  | 2024/06/19 22:56:08.548458 [info] go to http://172.18.0.2:80
adguard-unbound  | 2024/06/19 22:56:14.082571 [info] filtering: saving contents of filter 1 into "/opt/adguardhome/work/data/filters/1.txt"
adguard-unbound  | 2024/06/19 22:56:14.090937 [info] filtering: updated filter 1: 1375026 bytes, 68309 rules
adguard-unbound  | 2024/06/19 22:56:14.090947 [info] filtering: updated filter 1; rule count: 68309 (was 0)
adguard-unbound  | 2024/06/19 22:56:16.582046 [info] auth: user "admin" successfully logged in from ip 192.168.1.10
adguard-unbound  | 2024/06/20 10:13:02.881964 [info] AdGuard Home, version v0.107.51
adguard-unbound  | 2024/06/20 10:13:02.886748 [info] tls: using default ciphers
adguard-unbound  | 2024/06/20 10:13:02.894135 [info] safesearch default: disabled
adguard-unbound  | 2024/06/20 10:13:02.909269 [info] Initializing auth module: /opt/adguardhome/work/data/sessions.db
adguard-unbound  | 2024/06/20 10:13:02.911162 [info] auth: initialized.  users:1  sessions:1
adguard-unbound  | 2024/06/20 10:13:02.911185 [info] AdGuard Home updates are disabled
adguard-unbound  | 2024/06/20 10:13:02.911191 [info] web: initializing
adguard-unbound  | 2024/06/20 10:13:02.931154 [info] dnsproxy: cache: enabled, size 4096 b
adguard-unbound  | 2024/06/20 10:13:02.931305 [info] dnsproxy: max goroutines is set to 300
adguard-unbound  | 2024/06/20 10:13:02.931607 [info] Ratelimit is enabled and set to 20 rps, IPv4 subnet mask len 24, IPv6 subnet mask len 56
adguard-unbound  | 2024/06/20 10:13:02.931632 [info] dnsproxy: server will refuse requests of type ANY
adguard-unbound  | 2024/06/20 10:13:02.931639 [info] dnsproxy: cache: enabled, size 4194304 b
adguard-unbound  | 2024/06/20 10:13:02.931647 [info] dnsproxy: max goroutines is set to 300
adguard-unbound  | 2024/06/20 10:13:02.933409 [info] clients: processing addresses
adguard-unbound  | 2024/06/20 10:13:02.933423 [info] AdGuard Home is available at the following addresses:
adguard-unbound  | 2024/06/20 10:13:02.933868 [info] go to http://127.0.0.1:80
adguard-unbound  | 2024/06/20 10:13:02.933879 [info] go to http://[::1]:80
adguard-unbound  | 2024/06/20 10:13:02.933886 [info] go to http://172.18.0.2:80
adguard-unbound  | 2024/06/20 10:13:03.156544 [info] dnsproxy: starting dns proxy server
adguard-unbound  | 2024/06/20 10:13:03.156578 [info] dnsproxy: creating udp server socket 0.0.0.0:53
adguard-unbound  | 2024/06/20 10:13:03.156745 [info] dnsproxy: listening to udp://[::]:53
adguard-unbound  | 2024/06/20 10:13:03.156757 [info] dnsproxy: creating tcp server socket 0.0.0.0:53
adguard-unbound  | 2024/06/20 10:13:03.156789 [info] dnsproxy: listening to tcp://[::]:53
adguard-unbound  | 2024/06/20 10:13:03.156915 [info] dnsproxy: entering udp listener loop on [::]:53
adguard-unbound  | 2024/06/20 10:13:03.157044 [info] dnsproxy: entering tcp listener loop on [::]:53
administrator@ubuntu-svr:~/docker-adguard-unbound$ 
```

**Comment by hat3ph** [comment]
@FelixBorgel , any update? If not I will close this issue.

**Comment by hat3ph** [comment]
Ticket closed

**Comment by sypion** [comment]
Hi there! I'm encountering this same issue. I believe this is due to the fact I'm trying to run this on ARM64 environment. Do you have an image that supports that?

**Comment by hat3ph** [comment]
> Hi there! I'm encountering this same issue. I believe this is due to the fact I'm trying to run this on ARM64 environment. Do you have an image that supports that?

There is. Pls check out https://github.com/hat3ph/adguard-unbound/pkgs/container/adguard-unbound

**Comment by sypion** [comment]
Hmm, I thought that would fix the issue but it didn't. Thank you for directing me to the ARM image regardless. Only thing I'm getting in my log is:

```
exec /opt/entrypoint.sh: exec format error
exec /opt/entrypoint.sh: exec format error
exec /opt/entrypoint.sh: exec format error
exec /opt/entrypoint.sh: exec format error
exec /opt/entrypoint.sh: exec format error
exec /opt/entrypoint.sh: exec format error
exec /opt/entrypoint.sh: exec format error
exec /opt/entrypoint.sh: exec format error
```

With the following docker compose:

```
version: "3"

services:
  adguard-unbound:
    container_name: adguard-unbound
    image: ghcr.io/hat3ph/adguard-unbound:0.107.52
    restart: unless-stopped
    hostname: adguard-unbound
    # Volumes store your data between container upgrades
    volumes:
      - "./adguard/opt-adguard-work:/opt/adguardhome/work" # adguard container work directory
      - "./adguard/opt-adguard-conf:/opt/adguardhome/conf" # adguard container conf directory
      - "./unbound:/opt/unbound" # map custom unbound config
      - "/usr/share/dns:/usr/share/dns" # map DNSSEC key and root hints from dns-root-data package
    ports:
      - 53:53/tcp # AdGuard Home DNS connection
      - 53:53/udp # AdGuard Home DNS connection
      - 3000:3000/tcp # AdGuard Home install web panel. Can disable after installation is completed.
      - 85:80/tcp # AdGuard Home web panel HTTP
      #- 443:443/tcp # AdGuard Home web panel HTTPS
      #- 784:784/udp # AdGuard Home DNS-over-QUIC service
      #- 853:853/tcp # AdGuard Home DNS-over-TLS/QUIC service
      #- 67:67/udp # DHCP server
      #- 68:68/udp # DHCP server
      - 5053:5053/tcp # Uncomment to enable unbound access on local server
      - 5053:5053/udp # Uncomment to enable unbound access on local server
```

I am currently trying to run this on Debian.
